# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About me
    weight: 20
    identifier: aboutme

  - name: Education
    parent: aboutme
    url: '#education'
    weight: 10

  - name: Research Experience
    parent: aboutme
    url: '#research_experience'
    weight: 20

  - name: Teaching Experience
    parent: aboutme
    url: '#teaching_experience'
    weight: 30
  
  - name: Working Experience
    parent: aboutme
    url: '#working_experience'
    weight: 40
  
  - name: Awards & Scholarships
    parent: aboutme
    url: '#awards_scholarships'
    weight: 50
  
  - name: Extracurricular Activities
    parent: aboutme
    url: '#extracurricular'
    weight: 60

  - name: Publications
    url: publication
    weight: 30

  - name: People
    url: people
    weight: 40